spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/order_placing_meeting?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  session:
    store-type: none

server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 600 #seconds  默认30分钟，如果设置小于一分钟会赋值为一分钟

aiolos:
  security:
    browser:
      loginPage: /demo-login.html
#      loginType: REDIRECT
    code:
      image:
        length: 6
        width: 100
        url: /me,/user/*