oauth2:
  uri: http://127.0.0.1:8001/server/oauth

security:
  oauth2:
    client:
      client-id: client2
      client-secret: clientSecret2
      user-authorization-uri: ${oauth2.uri}/authorize
      access-token-uri: ${oauth2.uri}/token
    resource:
      jwt:
        key-uri: ${oauth2.uri}/token_key
server:
  port: 8003
  servlet:
    context-path: /client2

